import type { NextPage } from "next";
import Head from "next/head";
import { Counter } from "../components/Counter/Counter";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Counter description={"Counter"} defaultCount={0} />
      </main>
    </div>
  );
};

export default Home;
